### ISSUE TITLE
Estimate project size

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-simpledb#4]
There is no estimate in the project yet. We have to create one as explained [here](https://github.com/teamed/est)

**Comment by dmarkov** [comment]
@super132 please proceed, it's yours

**Comment by super132** [comment]
@dmarkov PR #7 fixed this issue, would you please close it? Thanks.

**Comment by yegor256** [comment]
@rultor deploy

**Comment by dmarkov** [comment]
@yegor256 Thanks all, I am closing

**Comment by dmarkov** [comment]
@super132 Much appreciated! **30 mins** was added to your account, payment ID `AP-23M29317051340939`, time spent is 167 hours and 30 mins. +30 to your rating, your total score is [+421](http://www.netbout.com/b/35282?open=rating)
